# Generated by Django 5.0.6 on 2024-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Madel')),
                ('photo', models.ImageField(upload_to='model/', verbose_name='Rasmi')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
    ]
